### ISSUE TITLE
Add option to add munin-node to a munin-server

### ISSUE THREAD

**Issue by deveth0** [geerlingguy/ansible-role-munin-node#6]
Hi,
Most likely I just didn't find it but it would be helpful if this role would allow me to add the new munin-node to my munin server through a delegate.

**Comment by geerlingguy** [comment]
@deveth0 - I typically manage my munin server completely separate, using my [`geerlingguy.munin` role](https://galaxy.ansible.com/geerlingguy/munin/) in a separate playbook (which would be triggered by Jenkins after building a new server and updating that munin server's inventory).

I do see a value in adding the ability to directly add the node to your munin server from this role, but since it's not how I have things configured for my infrastructure, and since that's a little bit more complex of a feature than I'd like to maintain in this role, I'm going to close this feature request.

It's definitely a feature that would be useful in many cases, and it might be good for someone else to either fork this role or build one separately to add that feature... but I don't want to add it myself.

**Comment by deveth0** [comment]
Fair enough :)
